Kg refactor
daipe-ai/feature-store-bundle pull request #17
Opened 2021-12-06 10:00 UTC by guderkar

2021-12-06 10:06 UTC, kutny commented on src/featurestorebundle/databricks/feature/reader/DatabricksFeatureStoreReader.py
> +        full_table_name = self.__table_names.get_latest_full_table_name(entity_name)
feature_names = feature_names or []

2021-12-06 10:07 UTC, kutny commented on src/featurestorebundle/databricks/feature/reader/DatabricksFeatureStoreReader.py
> +        full_table_name = self.__table_names.get_latest_full_table_name(entity_name)
Add this to address None value for list

2021-12-06 10:07 UTC, kutny commented on src/featurestorebundle/databricks/feature/reader/DatabricksFeatureStoreReader.py
> +        full_table_name = self.__table_names.get_latest_full_table_name(entity_name)
Apply to all readers pls

2021-12-06 10:15 UTC, kutny requested changes

2021-12-06 10:15 UTC, kutny commented on src/featurestorebundle/databricks/feature/writer/DatabricksFeatureStoreDataHandler.py
> +        features_data = self.__replace_decimal_types(config.data)
This is not a very safe approach :-(

2021-12-06 10:15 UTC, kutny commented on src/featurestorebundle/databricks/feature/writer/DatabricksFeatureStoreDataHandler.py
> +        except Exception:  # noqa
What about checking some more specific exception message?

2022-01-18 09:31 UTC, ds-lukaslangr requested changes

2022-02-09 19:18 UTC, merged